//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBike.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iBike.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge iBike File.
        /// </summary>
        internal static string Action_MergeiBikeFile {
            get {
                return ResourceManager.GetString("Action_MergeiBikeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open iBike File....
        /// </summary>
        internal static string Action_OpeniBikeFile {
            get {
                return ResourceManager.GetString("Action_OpeniBikeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aligned using: {0}.
        /// </summary>
        internal static string Label_AlignedUsing {
            get {
                return ResourceManager.GetString("Label_AlignedUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atm. Pres. (mbar).
        /// </summary>
        internal static string Label_ATMPress {
            get {
                return ResourceManager.GetString("Label_ATMPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV iBike File.
        /// </summary>
        internal static string Label_CSViBikeFile {
            get {
                return ResourceManager.GetString("Label_CSViBikeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        internal static string Label_GPS {
            get {
                return ResourceManager.GetString("Label_GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iBike.
        /// </summary>
        internal static string Label_iBike {
            get {
                return ResourceManager.GetString("Label_iBike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iBike Import.
        /// </summary>
        internal static string Label_iBikeImport {
            get {
                return ResourceManager.GetString("Label_iBikeImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string Label_Merge {
            get {
                return ResourceManager.GetString("Label_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Interval.
        /// </summary>
        internal static string Label_RecordInterval {
            get {
                return ResourceManager.GetString("Label_RecordInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilt.
        /// </summary>
        internal static string Label_Tilt {
            get {
                return ResourceManager.GetString("Label_Tilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        internal static string Label_Wind {
            get {
                return ResourceManager.GetString("Label_Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Scaling.
        /// </summary>
        internal static string Label_WindScale {
            get {
                return ResourceManager.GetString("Label_WindScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed.
        /// </summary>
        internal static string Label_WindSpeed {
            get {
                return ResourceManager.GetString("Label_WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} points/track.
        /// </summary>
        internal static string Label_XpointsPerTrack {
            get {
                return ResourceManager.GetString("Label_XpointsPerTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sec. recording.
        /// </summary>
        internal static string Label_XsecondRecording {
            get {
                return ResourceManager.GetString("Label_XsecondRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing activity found on same day.  For best results when merging iBike files with existing activities, please select existing activity and then:
        ///Edit &gt; Merge iBike File
        ///Continue importing anyway?.
        /// </summary>
        internal static string Text_ActivityExistsWarning {
            get {
                return ResourceManager.GetString("Text_ActivityExistsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported with iBike plugin ver. {0}: {1}.
        /// </summary>
        internal static string Text_ActivityNote {
            get {
                return ResourceManager.GetString("Text_ActivityNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the date from the iBike file..
        /// </summary>
        internal static string Text_CouldNotParseDate {
            get {
                return ResourceManager.GetString("Text_CouldNotParseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the recording interval rate from the iBike file..
        /// </summary>
        internal static string Text_CouldNotParseRecordInterval {
            get {
                return ResourceManager.GetString("Text_CouldNotParseRecordInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is unavailable.  Try Again?.
        /// </summary>
        internal static string Text_FileLocked {
            get {
                return ResourceManager.GetString("Text_FileLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Error occurred..
        /// </summary>
        internal static string Text_ImportError {
            get {
                return ResourceManager.GetString("Text_ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid iBike file..
        /// </summary>
        internal static string Text_InvalidFile {
            get {
                return ResourceManager.GetString("Text_InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching file found..
        /// </summary>
        internal static string Text_NoMatchingFileFound {
            get {
                return ResourceManager.GetString("Text_NoMatchingFileFound", resourceCulture);
            }
        }
    }
}
